import { z } from "zod";

import type { AgentAction } from "./types";

const ActionSchema = z
  .object({
    action: z.union([z.literal("create_task"), z.literal("move_task")]),
    title: z.string().optional(),
    description: z.string().optional(),
    priority: z.union([z.literal("low"), z.literal("medium"), z.literal("high")]).optional(),
    task_id: z.number().int().optional(),
    new_status: z
      .union([
        z.literal("backlog"),
        z.literal("todo"),
        z.literal("in_progress"),
        z.literal("blocked"),
        z.literal("review"),
        z.literal("done"),
        z.literal("cancelled"),
      ])
      .optional(),
    reason: z.string().optional(),
  })
  .strict();

const OutputSchema = z.object({
  actions: z.array(ActionSchema).max(5),
});

type PlannerResult = {
  model: string;
  actions: AgentAction[];
  error: "" | "opencode_failed" | "invalid_json";
};

const extractJsonObject = (text: string) => {
  const trimmed = text.trim();
  if (trimmed.startsWith("{")) return trimmed;
  const match = trimmed.match(/\{[\s\S]*\}/);
  if (!match) throw new Error("No JSON found");
  return match[0];
};

export const planActions = (input: {
  context: string;
  project: unknown;
  opencodeCmd?: string;
  opencodeModel?: string;
}): PlannerResult => {
  const cmd = input.opencodeCmd ?? process.env.OPENCODE_CMD ?? "opencode";
  const model = input.opencodeModel ?? process.env.OPENCODE_MODEL ?? "";

  const prompt = JSON.stringify(
    {
      instruction:
        "You are a backlog planner. Return ONLY valid JSON in the format {\"actions\":[...]} with up to 5 actions (create_task or move_task).",
      project: input.project,
      context: input.context,
    },
    null,
    0
  );

  const args = ["run", prompt];
  if (model) args.push("--model", model);

  const proc = Bun.spawnSync({ cmd: [cmd, ...args], stdout: "pipe", stderr: "pipe" });
  if (proc.exitCode !== 0) {
    return { model: "fallback", actions: fallbackActions(input.context), error: "opencode_failed" };
  }

  try {
    const out = new TextDecoder().decode(proc.stdout);
    const parsed = JSON.parse(extractJsonObject(out));
    const valid = OutputSchema.parse(parsed);
    return { model: model || "opencode-default", actions: valid.actions as AgentAction[], error: "" };
  } catch {
    return { model: "fallback", actions: fallbackActions(input.context), error: "invalid_json" };
  }
};

const fallbackActions = (context: string): AgentAction[] => {
  const lines = context
    .split("\n")
    .map((x) => x.trim())
    .filter(Boolean)
    .slice(0, 3);

  if (lines.length === 0) {
    return [
      {
        action: "create_task" as const,
        title: "Define next project steps",
        description: "Create initial backlog tasks.",
        priority: "medium" as const,
        reason: "Basic fallback",
      },
    ];
  }

  return lines.map((line) => ({
    action: "create_task" as const,
    title: `Plan: ${line.slice(0, 80)}`,
    description: "Generated by local fallback.",
    priority: "medium" as const,
    reason: "OpenCode unavailable",
  }));
};
